pub fn get_tutorial_text() -> Vec<String> {
  vec![
    "Welcome to cli-text-reader!".to_string(),
    "".to_string(),
    "Navigation:".to_string(),
    "j or ↓ = scroll down".to_string(),
    "k or ↑ = scroll up".to_string(),
    "PageDown = scroll down one page".to_string(),
    "PageUp = scroll up one page".to_string(),
    "".to_string(),
    "Search:".to_string(),
    "/ = search forward".to_string(),
    "? = search backward".to_string(),
    "n = next match".to_string(),
    "N = previous match".to_string(),
    "".to_string(),
    "Highlighting:".to_string(),
    "V = enter Visual Line mode (like Vim's SHIFT+V)".to_string(),
    "j/k in Visual mode = extend selection up/down".to_string(),
    ":hl = highlight selected lines".to_string(),
    ":rm-hl = remove highlights from selected lines".to_string(),
    ":clear-hl = clear all highlights".to_string(),
    ":export-hl = export all highlights to a file".to_string(),
    ":hlu = undo last highlight action".to_string(),
    "".to_string(),
    "Commands:".to_string(),
    ": then type command:".to_string(),
    "q = quit".to_string(),
    "z = toggle line highlighter".to_string(),
    "p = toggle progress".to_string(),
    "help or tutorial = show this tutorial".to_string(),
    "".to_string(),
    "Press any key to continue...".to_string(),
  ]
}
